#!/usr/bin/env bash
# Get process information using ps command and store it in a variable

process_info=$(ps aux --forest)
echo "User         PID  %CPU %MEM    VSZ   RSS TTY      STAT START   TIME COMMAND"
echo "$process_info"
