#!/usr/bin/env bash
# this
# Creates the file /var/run/myscript.pid containing its PID
# Displays To infinity and beyond indefinitely
# Displays I hate the kill command when receiving a SIGTERM signal
# Displays Y U no love me?! when receiving a SIGINT signal
# Deletes the file /var/run/myscript.pid and terminates itself 
#when receiving a SIGQUIT or SIGTERM signal

pid_file=/var/run/myscript.pid

echo $$ > $pid_file

function sigterm_handler {
  echo "I hate the kill command"
}

function sigint_handler {
  echo "Y U no love me?!"
}

trap sigterm_handler SIGTERM
trap sigint_handler SIGINT

echo "To infinity and beyond"

while true
do
  sleep 1
done

function quit_handler {
  rm $pid_file
  exit
}

trap quit_handler SIGQUIT
trap quit_handler SIGTERM
