#!/usr/bin/env bash
# a process script

pid_file="/var/run/my_process.pid"
process_name="manage_my_process"

start_process() {
    # Start the process in the background and save its PID to the PID file
    ./"$process_name" &
    echo $! > "$pid_file"
    echo "$process_name started"
}

stop_process() {
    # Stop the process using its PID from the PID file
    if [ -f "$pid_file" ]; then
        pid=$(cat "$pid_file")
        kill "$pid"
        rm "$pid_file"
        echo "$process_name stopped"
    else
        echo "$process_name is not running"
    fi
}

restart_process() {
    # Stop and start the process again
    stop_process
    start_process
}

if [ $# -eq 1 ]; then
    case "$1" in
        start)
            start_process
            ;;
        stop)
            stop_process
            ;;
        restart)
            restart_process
            ;;
        *)
            echo "Usage: $0 {start|stop|restart}"
            ;;
    esac
else
    echo "Usage: $0 {start|stop|restart}"
fi

